name: Django CI

on:
  push:
    branches: [ Group10DeveloperBranch ]
  pull_request:
    branches: [ Group10DeveloperBranch ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: ./simplyclip_backend
      run: |
        python -m pip install --upgrade pip
        pip install django pytest-django pytest-cov mixer flake8
    - name: Run Tests
      working-directory: ./simplyclip_backend
      run: |
        python -m pytest
